# Generated by .github/workflows/release.yml in radix29/gossms.
# Do not edit by hand — the next release overwrites this file.
class Gossms < Formula
  desc "Terminal reimplementation of SQL Server Management Studio"
  homepage "https://github.com/radix29/gossms"
  license "GPL-3.0-or-later"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/radix29/gossms/releases/download/v0.0.14/gossms_v0.0.14_darwin_arm64.tar.gz"
      sha256 "ffc9c69341716aad3ec5f7517ed571971b85b6e63a5bb7d00487f475d9577cbb"
    end
    on_intel do
      url "https://github.com/radix29/gossms/releases/download/v0.0.14/gossms_v0.0.14_darwin_amd64.tar.gz"
      sha256 "6a09221c52ebeb200e84f1e74f1c0643c6207e766002f2f5359b2a96e421c32f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/radix29/gossms/releases/download/v0.0.14/gossms_v0.0.14_linux_arm64.tar.gz"
      sha256 "91afbca8e9e3109e23fce9c43e152948bb9f1f6d4617745888a969d8685b4003"
    end
    on_intel do
      url "https://github.com/radix29/gossms/releases/download/v0.0.14/gossms_v0.0.14_linux_amd64.tar.gz"
      sha256 "aa5c62d7dabf5686df30c85ad3adfc66566042f25ac207b7489f2a77e3151eb4"
    end
  end

  def install
    bin.install "gossms"
    # Launcher and icons; only the Linux archives carry share/.
    share.install "share/applications", "share/icons" if OS.linux?
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gossms --version")
  end
end
