# Generated by .github/workflows/release.yml in radix29/gossms.
# Do not edit by hand — the next release overwrites this file.
class Gossms < Formula
  desc "Terminal reimplementation of SQL Server Management Studio"
  homepage "https://github.com/radix29/gossms"
  version "0.0.11"
  license "GPL-3.0-or-later"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/radix29/gossms/releases/download/v0.0.11/gossms_v0.0.11_darwin_arm64.tar.gz"
      sha256 "2ff1f135ee55b7dd616a19b68df501a46c6d643771b547be0bb62a6b780e1ca3"
    end
    on_intel do
      url "https://github.com/radix29/gossms/releases/download/v0.0.11/gossms_v0.0.11_darwin_amd64.tar.gz"
      sha256 "95d77b6fc06b0b2163217bc9fd339cd9e851e6480268c1bf93bb31e6fabad619"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/radix29/gossms/releases/download/v0.0.11/gossms_v0.0.11_linux_arm64.tar.gz"
      sha256 "641c606aa75c0ba44ff07ab5fcc55fc4c619a6ef29784236a2a9f77c5d58ab4f"
    end
    on_intel do
      url "https://github.com/radix29/gossms/releases/download/v0.0.11/gossms_v0.0.11_linux_amd64.tar.gz"
      sha256 "b182c23a687edb35292ee7d216a3d4591c75ca32e47a08fb9a4df07a1745b048"
    end
  end

  def install
    bin.install "gossms"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gossms --version")
  end
end
