# Generated by .github/workflows/release.yml in radix29/gossms.
# Do not edit by hand — the next release overwrites this file.
class Gossms < Formula
  desc "Terminal reimplementation of SQL Server Management Studio"
  homepage "https://github.com/radix29/gossms"
  version "0.0.12"
  license "GPL-3.0-or-later"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/radix29/gossms/releases/download/v0.0.12/gossms_v0.0.12_darwin_arm64.tar.gz"
      sha256 "521d12d1a01d0784a5ab5faf9bfab519779543034d699f0dd2275010e4ed49ee"
    end
    on_intel do
      url "https://github.com/radix29/gossms/releases/download/v0.0.12/gossms_v0.0.12_darwin_amd64.tar.gz"
      sha256 "52f28ea9c3de622a834f8406ab6f84da74bec6384fdb66a5f9e9439eb7293918"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/radix29/gossms/releases/download/v0.0.12/gossms_v0.0.12_linux_arm64.tar.gz"
      sha256 "1874f703fe929e15c009577c79edd5e72bb4fa911cdb3b8faacd7b0151cde24c"
    end
    on_intel do
      url "https://github.com/radix29/gossms/releases/download/v0.0.12/gossms_v0.0.12_linux_amd64.tar.gz"
      sha256 "62554f15b6e7d3900403945adb978d8e05e8898289747811f183c5ac75b07ad1"
    end
  end

  def install
    bin.install "gossms"
    # Launcher and icons; only the Linux archives carry share/.
    share.install "share/applications", "share/icons" if OS.linux?
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gossms --version")
  end
end
